/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Support for builtin filter-keytrans */
#define BUILTIN_FILTER_KEYTRANS 1

/* Support for builtin filter-mouse */
#define BUILTIN_FILTER_MOUSE 1

/* Support for builtin filter-save */
#define BUILTIN_FILTER_SAVE 1

/* Support for builtin filter-tcp */
#define BUILTIN_FILTER_TCP 1

/* Support for builtin input-cocoa */
/* #undef BUILTIN_INPUT_COCOA */

/* Support for builtin input-directx */
/* #undef BUILTIN_INPUT_DIRECTX */

/* Support for builtin input-file */
#define BUILTIN_INPUT_FILE 1

/* Support for builtin input-ipaq-ts */
/* #undef BUILTIN_INPUT_IPAQ_TS */

/* Support for builtin input-kii */
/* #undef BUILTIN_INPUT_KII */

/* Support for builtin input-linux-evdev */
#define BUILTIN_INPUT_LINUX_EVDEV 1

/* Support for builtin input-linux-joy */
#define BUILTIN_INPUT_LINUX_JOY 1

/* Support for builtin input-linux-kbd */
#define BUILTIN_INPUT_LINUX_KBD 1

/* Support for builtin input-linux-mouse */
#define BUILTIN_INPUT_LINUX_MOUSE 1

/* Support for builtin input-lk201 */
#define BUILTIN_INPUT_LK201 1

/* Support for builtin input-mouse */
#define BUILTIN_INPUT_MOUSE 1

/* Support for builtin input-null */
#define BUILTIN_INPUT_NULL 1

/* Support for builtin input-pcjoy */
/* #undef BUILTIN_INPUT_PCJOY */

/* Support for builtin input-quartz */
/* #undef BUILTIN_INPUT_QUARTZ */

/* Support for builtin input-spaceorb */
#define BUILTIN_INPUT_SPACEORB 1

/* Support for builtin input-stdin */
#define BUILTIN_INPUT_STDIN 1

/* Support for builtin input-tcp */
#define BUILTIN_INPUT_TCP 1

/* Support for builtin input-vgl */
/* #undef BUILTIN_INPUT_VGL */

/* Support for builtin input-x */
#define BUILTIN_INPUT_X 1

/* Support for builtin input-zaurus */
/* #undef BUILTIN_INPUT_ZAURUS_TS */

/* Define if CC can compile amask opcode (DEC) */
/* #undef CC_CAN_AMASK */

/* Define if CC can compile cpuid opcode (Intel) */
/* #undef CC_CAN_CPUID */

/* Define to 1 to use win32 `GetSystemTimeAsFileTime' for ggCurTime. */
/* #undef GG_CURTIME_USE_GETSYSTEMTIMEASFILETIME */

/* Define to 1 to use `gettimeofday' for ggCurTime. */
#define GG_CURTIME_USE_GETTIMEOFDAY 1

/* Define if you want memory usage debugging code */
/* #undef GG_MEMDEBUG */

/* Tell libgg to define integer types for building */
/* #undef GG_NEED_INTTYPES */

/* Define to 1 if the `usleep' function limits usecs value. */
/* #undef GG_USLEEP_999999 */

/* Define to 1 to use `select' for ggUSleep/ggUSlumber. */
/* #undef GG_USLEEP_USE_SELECT */

/* Define to 1 to use `usleep' for ggUSleep/ggUSlumber. */
#define GG_USLEEP_USE_USLEEP 1

/* Define to 1 to use win32 `Sleep' for ggUSleep/ggUSlumber. */
/* #undef GG_USLEEP_USE_W32SLEEP */

/* Define to 1 if the `usleep' function returns void. */
/* #undef GG_USLEEP_VOID */

/* Full path of configuration directory (including tag) */
#define GIICONFDIR "pAtHTAg/usr/local/etc/ggi"

/* Name of LibGII main conf file */
#define GIICONFFILE "libgii.conf"

/* Used to s// in path to libgii.conf */
#define GIIPATHTAG "pAtHTAg"

/* Define to length of below tag */
#define GIITAGLEN 7

/* Define to 1 if you have the <ApplicationServices/ApplicationServices.h>
   header file. */
/* #undef HAVE_APPLICATIONSERVICES_APPLICATIONSERVICES_H */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the <asm/sharp_ts.h> header file. */
/* #undef HAVE_ASM_SHARP_TS_H */

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have the `atexit' function. */
#define HAVE_ATEXIT 1

/* Define to 1 if you have the `connect' function. */
#define HAVE_CONNECT 1

/* Define to 1 if you have the <c_asm.h> header file. */
/* #undef HAVE_C_ASM_H */

/* Define to 1 if you have the <dinput.h> header file. */
/* #undef HAVE_DINPUT_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if your system has dlopen */
#define HAVE_DLOPEN 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the `fcntl' function. */
#define HAVE_FCNTL 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the `GetSystemTimeAsFileTime' function. */
/* #undef HAVE_GETSYSTEMTIMEASFILETIME */

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if the system has the type `intptr_t'. */
#define HAVE_INTPTR_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `c' library (-lc). */
/* #undef HAVE_LIBC */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <link.h> header file. */
#define HAVE_LINK_H 1

/* Define to 1 if you have the <linux/h3600_ts.h> header file. */
/* #undef HAVE_LINUX_H3600_TS_H */

/* Define to 1 if you have the <linux/input.h> header file. */
#define HAVE_LINUX_INPUT_H 1

/* Define to 1 if you have the <linux/joystick.h> header file. */
#define HAVE_LINUX_JOYSTICK_H 1

/* Define to 1 if you have the <linux/kdev_t.h> header file. */
#define HAVE_LINUX_KDEV_T_H 1

/* Define to 1 if you have the <linux/kd.h> header file. */
#define HAVE_LINUX_KD_H 1

/* Define to 1 if you have the <linux/keyboard.h> header file. */
#define HAVE_LINUX_KEYBOARD_H 1

/* Define to 1 if you have the <linux/major.h> header file. */
#define HAVE_LINUX_MAJOR_H 1

/* Define to 1 if you have the <linux/vt.h> header file. */
#define HAVE_LINUX_VT_H 1

/* Define to 1 if you have the <mach-o/dyld.h> header file. */
/* #undef HAVE_MACH_O_DYLD_H */

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define if your libc has a __malloc_hook for debug */
/* #undef HAVE_MALLOC_HOOK */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have the `nanosleep' function */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define if there is no way to check CPU ID */
#define HAVE_NO_CPUID 1

/* Undefine when there is an implementation for ggGetSwarType */
#define HAVE_NO_SWARTYPE_IMPLEMENTATION 1

/* Define to 1 if you have the `NSCreateObjectFileImageFromFile' function. */
/* #undef HAVE_NSCREATEOBJECTFILEIMAGEFROMFILE */

/* Define to 1 if you have the `NSDestroyObjectFileImage' function. */
/* #undef HAVE_NSDESTROYOBJECTFILEIMAGE */

/* Define to 1 if you have the `on_exit' function. */
#define HAVE_ON_EXIT 1

/* Define to 1 if you have the `pclose' function. */
#define HAVE_PCLOSE 1

/* Define to 1 if you have the `pipe' function. */
#define HAVE_PIPE 1

/* Define to 1 if you have the `popen' function. */
#define HAVE_POPEN 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the `raise' function. */
#define HAVE_RAISE 1

/* Define to 1 if you have the `readlink' function. */
#define HAVE_READLINK 1

/* Define to 1 if you have the <sched.h> header file. */
#define HAVE_SCHED_H 1

/* Define if you have the sched_yield function */
#define HAVE_SCHED_YIELD 1

/* Define to 1 if you have the <shlobj.h> header file. */
/* #undef HAVE_SHLOBJ_H */

/* Define to 1 if you have the `sigaction' function. */
#define HAVE_SIGACTION 1

/* Define to 1 if you have the `siginterrupt' function. */
#define HAVE_SIGINTERRUPT 1

/* Define to 1 if you have the `signal' function. */
#define HAVE_SIGNAL 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `Sleep' function. */
/* #undef HAVE_SLEEP */

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if socklen_t type is supported. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlcat' function. */
/* #undef HAVE_STRLCAT */

/* Define to 1 if you have the `strlcpy' function. */
/* #undef HAVE_STRLCPY */

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strncat' function. */
#define HAVE_STRNCAT 1

/* Define to 1 if you have the `strncpy' function. */
#define HAVE_STRNCPY 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the `strtoull' function. */
#define HAVE_STRTOULL 1

/* Define to 1 if `st_rdev' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_RDEV 1

/* Define to 1 if your `struct stat' has `st_rdev'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_RDEV' instead. */
#define HAVE_ST_RDEV 1

/* Define to 1 if you have the <sys/fbio.h> header file. */
/* #undef HAVE_SYS_FBIO_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/io.h> header file. */
#define HAVE_SYS_IO_H 1

/* Define to 1 if you have the <sys/kd.h> header file. */
#define HAVE_SYS_KD_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/sysctl.h> header file. */
#define HAVE_SYS_SYSCTL_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H 1

/* Define to 1 if you have the <sys/vt.h> header file. */
#define HAVE_SYS_VT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define if sys/ioctl.h defines TIOCMSET */
#define HAVE_TIOCMSET 1

/* Define to 1 if the system has the type `uintptr_t'. */
#define HAVE_UINTPTR_T 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the <vgl.h> header file. */
/* #undef HAVE_VGL_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the <winsock2.h> header file. */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if you have the <winsock.h> header file. */
/* #undef HAVE_WINSOCK_H */

/* Define to 1 if you have the <X11/extensions/xf86dga.h> header file. */
#define HAVE_X11_EXTENSIONS_XF86DGA_H 1

/* Support for xf86dga in input-x */
#define HAVE_XF86DGA 1

/* Define to 1 if you have the `_exit' function. */
#define HAVE__EXIT 1

/* Set to install path */
#define INSTALL_PREFIX "/usr/local"

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define LT_OBJDIR ".libs/"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://www.ggi-project.org/contact.html"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libgii"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libgii 1.0.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libgii"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.2"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `SSIZE_T', as computed by sizeof. */
#define SIZEOF_SSIZE_T 4

/* The size of a `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 4

/* The size of a `__darwin_ssize_t', as computed by sizeof. */
#define SIZEOF___DARWIN_SSIZE_T 0

/* The size of a `__int64', as computed by sizeof. */
#define SIZEOF___INT64 0

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if symbols are prefixed with underscore */
/* #undef SYMBOL_UNDERSCORE */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
