/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Support for builtin default renderers */
#define BUILTIN_DEFAULT 1

/* Support for builtin fbdev-accel */
#define BUILTIN_DEFAULT_FBDEV_ACCEL 1

/* Support for builtin default-fbdev-directfb */
/* #undef BUILTIN_DEFAULT_FBDEV_DIRECTFB */

/* Support for builtin default-kgi-accel */
/* #undef BUILTIN_DEFAULT_KGI_ACCEL */

/* Support for builtin display targets */
#define BUILTIN_DISPLAY 1

/* Support for builtin display-aa */
/* #undef BUILTIN_DISPLAY_AA */

/* Support for builtin display-directx */
/* #undef BUILTIN_DISPLAY_DIRECTX */

/* Support for builtin display-fbdev */
#define BUILTIN_DISPLAY_FBDEV 1

/* Support for builtin display-file */
#define BUILTIN_DISPLAY_FILE 1

/* Support for builtin display-glide */
/* #undef BUILTIN_DISPLAY_GLIDE */

/* Support for builtin display-ipc */
#define BUILTIN_DISPLAY_IPC 1

/* Support for builtin display-kgi */
/* #undef BUILTIN_DISPLAY_KGI */

/* Support for builtin display-lcd823 */
/* #undef BUILTIN_DISPLAY_LCD823 */

/* Support for builtin display-libkgi */
/* #undef BUILTIN_DISPLAY_LIBKGI */

/* Support for builtin display-memory */
#define BUILTIN_DISPLAY_MEMORY 1

/* Support for builtin display-monotext */
#define BUILTIN_DISPLAY_MONOTEXT 1

/* Support for builtin display-multi */
#define BUILTIN_DISPLAY_MULTI 1

/* Support for builtin display-palemu */
#define BUILTIN_DISPLAY_PALEMU 1

/* Support for builtin display-quartz */
/* #undef BUILTIN_DISPLAY_QUARTZ */

/* Support for builtin display-sub */
#define BUILTIN_DISPLAY_SUB 1

/* Support for builtin display-svgalib */
/* #undef BUILTIN_DISPLAY_SVGALIB */

/* Support for builtin display-tele */
#define BUILTIN_DISPLAY_TELE 1

/* Support for builtin display-terminfo */
#define BUILTIN_DISPLAY_TERMINFO 1

/* Support for builtin display-tile */
#define BUILTIN_DISPLAY_TILE 1

/* Support for builtin display-trueemu */
#define BUILTIN_DISPLAY_TRUEEMU 1

/* Support for builtin display-vcsa */
#define BUILTIN_DISPLAY_VCSA 1

/* Support for builtin display-vgl */
/* #undef BUILTIN_DISPLAY_VGL */

/* Support for builtin display-x */
#define BUILTIN_DISPLAY_X 1

/* Support for builtin helper-linvtsw */
#define BUILTIN_HELPER_LINVTSW 1

/* Support for builtin helper-mansync */
#define BUILTIN_HELPER_MANSYNC 1

/* Support for builtin helper-vgagl */
/* #undef BUILTIN_HELPER_VGAGL */

/* Support for builtin helper-x-dbe */
#define BUILTIN_HELPER_X_DBE 1

/* Support for builtin helper-x-dga */
#define BUILTIN_HELPER_X_DGA 1

/* Support for builtin helper-x-evi */
#define BUILTIN_HELPER_X_EVI 1

/* Support for builtin helper-x-shm */
#define BUILTIN_HELPER_X_SHM 1

/* Support for builtin helper-x-vidmode */
#define BUILTIN_HELPER_X_VIDMODE 1

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Where to look for DirectFB modules */
/* #undef DIRECTFB_DRIVER_DIR */

/* Defines for SWAR selection */
/* #undef DO_SWAR_3DNOW */

/* Defines for SWAR selection */
/* #undef DO_SWAR_64BITC */

/* Defines for SWAR selection */
/* #undef DO_SWAR_MMX */

/* Defines for SWAR selection */
/* #undef DO_SWAR_MVI */

/* Defines for SWAR selection */
#define DO_SWAR_NONE 1

/* Defines for SWAR selection */
/* #undef DO_SWAR_VIS */

/* Tag plus path to config dir */
#define GGICONFDIR "pAtHTAg/usr/local/etc/ggi"

/* Name of LibGGI master config file */
#define GGICONFFILE "libggi.conf"

/* Tag to identify path to $ggi_conffile */
#define GGIPATHTAG "pAtHTAg"

/* The length of the tag */
#define GGITAGLEN 7

/* Tell libgg to define integer types when building */
/* #undef GG_NEED_INTTYPES */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <ApplicationServices/ApplicationServices.h>
   header file. */
/* #undef HAVE_APPLICATIONSERVICES_APPLICATIONSERVICES_H */

/* Define to 1 if you have the <asm/sharp_ts.h> header file. */
/* #undef HAVE_ASM_SHARP_TS_H */

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define if you have the <curses.h> header file. */
/* #undef HAVE_CURSES_H */

/* Define to 1 if you have the <ddraw.h> header file. */
/* #undef HAVE_DDRAW_H */

/* Define if you have <directfb.h> header file */
/* #undef HAVE_DIRECTFB_H */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <ggi/gii.h> header file. */
#define HAVE_GGI_GII_H 1

/* Define to 1 if you have the <glide/glide.h> header file. */
/* #undef HAVE_GLIDE_GLIDE_H */

/* Define to 1 if you have the <glide.h> header file. */
/* #undef HAVE_GLIDE_H */

/* Define to 1 if you have the `herror' function. */
#define HAVE_HERROR 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <kgimon.h> header file. */
/* #undef HAVE_KGIMON_H */

/* Define to 1 if you have the `kill' function. */
#define HAVE_KILL 1

/* Define to 1 if you have the `c' library (-lc). */
#define HAVE_LIBC 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <linux/h3600_ts.h> header file. */
/* #undef HAVE_LINUX_H3600_TS_H */

/* Define to 1 if you have the <linux/kdev_t.h> header file. */
#define HAVE_LINUX_KDEV_T_H 1

/* Define to 1 if you have the <linux/kd.h> header file. */
#define HAVE_LINUX_KD_H 1

/* Define to 1 if you have the <linux/major.h> header file. */
#define HAVE_LINUX_MAJOR_H 1

/* Define to 1 if you have the <linux/vt.h> header file. */
#define HAVE_LINUX_VT_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define if you have the <ncurses.h> header file */
#define HAVE_NCURSES_H 1

/* Define if you have the <ncurses/ncurses.h> header file. */
/* #undef HAVE_NCURSES_NCURSES_H */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define if struct fb_fix_screeninfo has an 'accel' member. */
#define HAVE_NEW_FBDEV 1

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the `random' function. */
#define HAVE_RANDOM 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `sigpending' function. */
#define HAVE_SIGPENDING 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define if socklen_t type is supported. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlcat' function. */
/* #undef HAVE_STRLCAT */

/* Define to 1 if you have the `strlcpy' function. */
/* #undef HAVE_STRLCPY */

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strncat' function. */
#define HAVE_STRNCAT 1

/* Define to 1 if you have the `strncpy' function. */
#define HAVE_STRNCPY 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if you have the `strtoull' function. */
#define HAVE_STRTOULL 1

/* Define to 1 if `st_rdev' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_RDEV 1

/* Define to 1 if your `struct stat' has `st_rdev'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_RDEV' instead. */
#define HAVE_ST_RDEV 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/fbio.h> header file. */
/* #undef HAVE_SYS_FBIO_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/ipc.h> header file. */
#define HAVE_SYS_IPC_H 1

/* Define to 1 if you have the <sys/kd.h> header file. */
#define HAVE_SYS_KD_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/shm.h> header file. */
#define HAVE_SYS_SHM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define HAVE_SYS_UN_H 1

/* Define to 1 if you have the <sys/vt.h> header file. */
#define HAVE_SYS_VT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if Unix domain sockets are supported. */
#define HAVE_UNIX_DOMAIN_SOCKET 1

/* Define to 1 if you have the <vgl.h> header file. */
/* #undef HAVE_VGL_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the <winsock2.h> header file. */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if you have the <winsock.h> header file. */
/* #undef HAVE_WINSOCK_H */

/* Define to 1 if you have the <X11/extensions/Xdbe.h> header file. */
#define HAVE_X11_EXTENSIONS_XDBE_H 1

/* Define to 1 if you have the <X11/extensions/XEVI.h> header file. */
#define HAVE_X11_EXTENSIONS_XEVI_H 1

/* Define to 1 if you have the <X11/extensions/xf86dga.h> header file. */
#define HAVE_X11_EXTENSIONS_XF86DGA_H 1

/* Define to 1 if you have the <X11/extensions/xf86vmode.h> header file. */
#define HAVE_X11_EXTENSIONS_XF86VMODE_H 1

/* Define to 1 if you have the <X11/extensions/xf86vmstr.h> header file. */
#define HAVE_X11_EXTENSIONS_XF86VMSTR_H 1

/* Define to 1 if you have the <X11/extensions/XShm.h> header file. */
#define HAVE_X11_EXTENSIONS_XSHM_H 1

/* Define to 1 if you have the `XInitImage' function. */
#define HAVE_XINITIMAGE 1

/* Define to the sub-directory in which libtool stores uninstalled libraries.
   */
#define LT_OBJDIR ".libs/"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://www.ggi-project.org/contact.html"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libggi"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libggi 2.2.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libggi"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.2.2"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
