.TH "input-quartz" 7 "2007-01-10" "libgii-1.0.x" GGI
.SH NAME
\fBinput-quartz\fR : MacOSX Quartz/Carbon Input
.SH SYNOPSIS
.nb
.nf
input-quartz
.fi

.SH DESCRIPTION
input-quartz, a native input library for MacOSX. It uses the
quartz/carbon API. It is used by display-quartz(7) and not
standalone usable.

MacOSX 10.2.8 (Jaguar) or newer is required.
.SH FEATURES
.IP \(bu 4
Generates evPtr* and evKey* events.
.PP
