.TH "input-x" 7 "2005-08-11" "libgii-1.0.x" GGI
.SH NAME
\fBinput-x\fR : X11 standalone input
.SH SYNOPSIS
.nb
.nf
input-x [-nokeyfocus]

input-xwin

input-xf86dga
.fi

.SH DESCRIPTION
input-x and input-xwin, an input target for X11 Environments.
input-x opens a X11 window to receive input from and
works standalone.

input-xwin and input-xf86dga is used by libggi's \f(CWdisplay-x(7)\fR.
They are NOT intended to be directly used by applications.

X11R5 is required.
.SH OPTIONS
.TP
\f(CW-nokeyfocus\fR
Disables keyboard focus. See the XSetInputFocus(3X11) manpage for the details
on keyboard focus, where \fIfocus\fR is a 'window' and \fIrevert_to\fR is 'RevertToParent'.

.PP
