.TH "xsendbut" 1 "2004-10-14" "libgii-1.0.x" GGI
.SH NAME
\fBxsendbut\fR : converts LibGII mhub data to X button events.
.SH SYNOPSIS
.nb
.nf
xsendbut
.fi

.SH DESCRIPTION
\fBxsendbut\fR reads \fBmhub(1)\fR data from stdin and triggers button press
events on the X target it is running on.
.SH OPTIONS
None
.SH SEE ALSO
\f(CWmhub(1)\fR, \f(CWlibgii(7)\fR
